### PR TITLE
re-adding headers to examples

### PR DESCRIPTION
**Pull request by rymo**
I had to partially revert the examples to get them to compile locally.

### CODE REVIEW

**Comment by jersey99** [comment]
Makes sense, I do that as well. You need not include matrixsslApi.h as it is already included in httpsclient-particle.h. 

The problem is in keeping this compatible between WebIDE and local build with spark firmware. I have been thinking of maintaining a different branch, one for local and one for WebIDE build. I sort of already do that. Any thoughts?

**Comment by rymo** [comment]
Is there an `ifdef` we can check for the WebIDE and conditionally include the conflicting parts only from command line?  Perhaps my commit should be directed toward readme.md instead!

**Comment by technobly** [comment]
Aha, I see we did the same thing.  Check out my PR: https://github.com/glowfishAPI/httpsclient-particle/pull/3 This is the more correct way to do the headers so that you can click on an example in the library, and then click the USE THIS EXAMPLE button to make a copy in your APPs that will compile without the user having to do anything extra.

For local compile this header style is an issue, but most advanced users that would be compiling locally should be aware of this difference... and you also have to rearrange the folders so that it compiles correctly.  So perhaps a few notes in the README.md for how to juggle the differences to compile locally would be enough?

**Comment by rymo** [comment]
@technobly I see!  I cloned your fork and got it to compile on the web; closing this PR in favor of yours at #3 .

**Comment by rymo** [comment]
for suggested readme edits, see #4

**Pull request closed without merging**
